baseurl = "http://zurtr.com/"
title = "Zurtr"
languageCode = "en-us"
theme = "vec"


# Enable comments by entering your Disqus shortname
disqusShortname = "Your Disqus shortname"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "Your Google Analytics tracking code"

[params]
  Keywords = "key, 关键字, キーワード"
  Description = "There are some words to describe your site"

  Avater = "/img/logo.png"
  SelfIntro = "Just a worm, seek for true, live in shadow, no more..."
  Email = "contact@zurtr.com"

  GithubID = "Zurtr"
  TwitterID = "Your Twitter ID"
  FacebookID = "Your Facebook ID"
  LinkedInID = "Your LinkedIn ID"
  GoogleplusID = "Your Googleplus ID"
